# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Requirement
  description: Requirement
  icon: 'cottage'
  tags:
    - Image
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  req_title: string
  requirements: [bookshop:structure:RequirementCard]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  req_title:
    options:
      preview:
        icon: 'text'
        text:
          - key: req_title
          - 'Requirement Title'
        subtext:
          - 'Update Title'
