# Metadata about this component, to be used in the CMS
spec:
  structures:
    - cards
  label: What We Do Card
  description: What We Do Card Information
  icon: 'cottage'
  tags:
    - Image
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  image: /w1.png
  heading: Wir bereiten Dich auf Deine Kontrollfahrt vor
  body: >
          Eine seriöse Vorbereitung mit einem erfahrenen Fahrlehrer/-in ist sinnvoll, denn eine nicht bestandene Kontrollfahrt bzw. Kontrollprüfung kann nicht wiederholt werden. Somit müsstest du mit der gesamten Prüfung von vorne beginnen. Jedes Jahr kommen viele Besitzer ausländischer Führerausweise zu uns, damit ihr Ausweis in einen Schweizerischen umgetauscht werden kann. Melde dich bei uns, wir helfen dir gerne weiter.
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  heading:
    type: text
    label: heading
    options:
      preview:
        icon: 'text'
        text:
          - key: heading
        subtext:
          - 'Update Heading'
  image:
    options:
      preview:
        icon: 'image'
        text:
          - 'Image'
        subtext:
          - key: image
          - 'Update image'
        image:
          - key: image
  body:
    type: textarea
    label: body
    options:
      preview:
        icon: 'text'
        text:
          - key: body
        subtext:
          - 'Update Body'