# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Contact Form
  description: Contact Form of This Site
  icon: 'cottage'
  tags:
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  left_text: Hast du Fragen oder benötigst du weitere Informationen? \n Wir freuen uns auf deine Kontaktaufnahme.
  button_link: /kontakt
  button_text: Jetzt kontaktieren
  address: Zürcher­strasse 9 \n 8952 Schlieren
  opening_days: "Montag - Freitag :"
  opening_hours: 08:00 - 20:00
  
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  left_text:
    options:
      preview:
        icon: 'text'
        text:
          - key: left_text
          - 'Left Text'
        subtext:
          - 'Update Left text'
  button_text:
    options:
      preview:
        icon: 'text'
        text:
          - key: button_text
          - 'button Text'
        subtext:
          - 'Update text'
  button_link:
    options:
      preview:
        icon: 'text'
        text:
          - key: button_link
          - 'Link Text'
        subtext:
          - 'Update text'
  address:
    options:
      preview:
        icon: 'text'
        text:
          - key: address
          - 'address Text'
        subtext:
          - 'Update text'
  opening_days:
    options:
      preview:
        icon: 'text'
        text:
          - key: opening_days
          - 'opening days'
        subtext:
          - 'Update opening days'
  opening_hours:
    options:
      preview:
        icon: 'text'
        text:
          - key: opening_hours
          - 'opening hours'
        subtext:
          - 'Update opening hours'