# Metadata about this component, to be used in the CMS
spec:
  structures:
    - kurse_block
  label: About Team
  description: About Team of This Site
  icon: 'cottage'
  tags:
    - Image
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  Titel: "CZV Weiterbildung"
  Kurzbeschreibung: "Die CZV-Weiterbildung frischt alle fünf Jahre die Qualifikation von Berufschauffeuren auf. Der Kurs fördert sichere, wirtschaftliche und kundenfreundliche Fahrkompetenzen und behandelt aktuelle rechtliche, technische und gesundheitliche Themen."
  Kursfoto: "/Frame 5.png"
  Fotoalttag: "CZV Weiterbildung"
  Beschreibung: "Die CZV-Weiterbildung (Chauffeurzulassungsverordnung) ist eine gesetzlich vorgeschriebene Fortbildung für Berufschauffeure, die gewerblich Personen oder Güter befördern. Alle fünf Jahre müssen Chauffeure an 35 Stunden Weiterbildung teilnehmen, um ihre Qualifikation aufrechtzuerhalten und ihre Kenntnisse aufzufrischen. Der Kurs zielt darauf ab, Fahrern aktuelles Wissen und Fähigkeiten für einen sicheren, ökologischen und serviceorientierten Berufsalltag zu vermitteln."
  Teilnehmer: "maximal 12"
  Kursort: "Fahrschule Loyal"
  Dauer: "1 Tag"
  Inhalt: 
    - "Sicherheit im Strassenverkehr - Dieser Teil behandelt die Auffrischung von Wissen zur Unfallverhütung, das defensive Fahrverhalten, das richtige Verhalten bei Unfällen und neuen Sicherheitsstandards sowie die Ladungssicherung."
    - "Ökologisches Fahren - Es werden Techniken zur kraftstoffsparenden Fahrweise, Methoden zur Reduktion von Emissionen und Verschleiss sowie Tipps für eine umweltschonende Fahrweise vermittelt."
    - "Rechtliche Neuerungen - Die Teilnehmer werden über aktuelle gesetzliche Änderungen und Vorschriften für den Güter- und Personentransport informiert, wie beispielsweise Anpassungen bei Lenk- und Ruhezeiten."
    - "Kundenorientiertes Verhalten - Hier wird die Kommunikation mit Kunden und Fahrgästen thematisiert, der professionelle Umgang mit Beschwerden sowie Tipps für eine serviceorientierte Kundenbetreuung."
    - "Gesundheit und Wohlbefinden - Es wird Wissen über Stressbewältigung, Prävention von gesundheitlichen Belastungen im Fahrerberuf und Tipps zur Förderung von Gesundheit und Fitness vermittelt."
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  Titel:
    options:
      preview:
        icon: 'text'
        text:
          - key: Titel
          - 'Header Text'
        subtext:
          - 'Update Titel text'
  Kurzbeschreibung:
    type: textarea
    options:
      preview:
        icon: 'text'
        text:
          - key: Kurzbeschreibung
          - 'Header Text'
        subtext:
          - 'Update Kurzbeschreibung text'
  Kursfoto:
    options:
      preview:
        icon: 'image'
        text:
          - key: Kursfoto
          - 'Kurs Image'
        subtext:
          - key: Kursfoto
          - 'Update Kurs Image'
        image:
          - key: Kursfoto
  Fotoalttag:
    type: text
    options:
      preview:
        icon: 'text'
        text:
          - key: Fotoalttag
          - 'Kurs Fotoalttag'
        subtext:
          - 'Update Fotoalttag '
  Beschreibung:
    type: textarea
    options:
      preview:
        icon: 'textarea'
        text:
          - key: Beschreibung
          - 'Kurs Beschreibung'
        subtext:
          - 'Update Kurs Beschreibung'
  Teilnehmer:
    type: text
    options:
      preview:
        icon: 'text'
        text:
          - key: Teilnehmer
          - 'Maximale Teilnehmer'
  Kursort:
    type: text
    options:
      preview:
        icon: 'text'
        text:
          - key: Kursort
          - 'Kurs Ort'
        subtext:
          - 'Update Kursort text'
  Dauer:
    type: text
    options:
      preview:
        icon: 'text'
        text:
          - key: Dauer
          - 'Kurs Dauer'
        subtext:
          - 'Update Kurs Dauer text'
  Inhalt:
    type: list
    label: Kurs Inhalt
    item:
      type: group
      label: Kurs Inhalt Punkt
      options:
        preview:
          icon: 'text'
          subtext:
            - 'Kurs Inhalt Punkt Text'