# Metadata about this component, to be used in the CMS
spec:
  structures:
    - kurse_block
  label: About Team
  description: About Team of This Site
  icon: 'cottage'
  tags:
    - Image
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  Titel: "CZV Weiterbildung"
  Kurzbeschreibung: "Die CZV-Weiterbildung frischt alle fünf Jahre die Qualifikation von Berufschauffeuren auf. Der Kurs fördert sichere, wirtschaftliche und kundenfreundliche Fahrkompetenzen und behandelt aktuelle rechtliche, technische und gesundheitliche Themen."
  Kursfoto: "/Frame 5.png"
  Fotoalttag: "CZV Weiterbildung"
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  Titel:
    options:
      preview:
        icon: 'text'
        text:
          - key: Titel
          - 'Header Text'
        subtext:
          - 'Update Titel text'
  Kurzbeschreibung:
    type: textarea
    options:
      preview:
        icon: 'text'
        text:
          - key: Kurzbeschreibung
          - 'Header Text'
        subtext:
          - 'Update Kurzbeschreibung text'
  Kursfoto:
    options:
      preview:
        icon: 'image'
        text:
          - key: Kursfoto
          - 'Kurs Image'
        subtext:
          - key: Kursfoto
          - 'Update Kurs Image'
        image:
          - key: Kursfoto
  Fotoalttag:
    type: text
    options:
      preview:
        icon: 'text'
        text:
          - key: Fotoalttag
          - 'Kurs Fotoalttag'
        subtext:
          - 'Update Fotoalttag '