# Metadata about this component, to be used in the CMS
spec:
  structures:
    - left_timeline
    - right_timeline
  label: Sequence Time Line Card
  description: Sequence Time Line Card
  icon: 'cottage'
  tags:
    - Image
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  icon: /document-time_icon.svg
  title: Einreichung
  description: Reiche die erforderlichen Unterlagen ein.
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    type: text
    label: title
    options:
      preview:
        icon: 'text'
        text:
          - key: title
        subtext:
          - 'Update title'
  icon:
    options:
      preview:
        icon: 'image'
        text:
          - 'Image'
        subtext:
          - key: icon
          - 'Update Icon'
        image:
          - key: icon
  description:
    type: textarea
    label: description
    options:
      preview:
        icon: 'text'
        text:
          - key: description
        subtext:
          - 'Update description'