spec:
  structures:
    - content_blocks
  label: Review Container
  description: Main call-to-action section with image, heading, description, and button
  icon: 'vertical_split'
  tags:
    - Text
    - Button

blueprint:
  title: "Google Rezensionen"
  subtitle: "Was unsere Fahrschüler über Fahrschule Loyal sagen"
  button_text: "Rezension schreiben"
preview:

_inputs:
  title:
    type: text
    label: Title
    options:
      preview:
        icon: 'short_text'
        text:
          - key: title
        subtext:
          - 'Title'
  subtitle:
    type: text
    label: Sub Title
    options:
      preview:
        icon: 'short_text'
        text:
          - key: subtitle
        subtext:
          - 'Sub Title top for the section'
  button_text:
    type: text
    label: Button title
    options:
      preview:
        icon: 'short_text'
        text:
          - key: button_text
        subtext:
          - 'Button Text'
