# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: AboutBanner
  description: AboutBanner of This Site
  icon: 'cottage'
  tags:
    - Image
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  image:
    image_path: /heroimg.jpeg
    alt_text: Banner Image
  header: Über mich
  description: |
      Nothelfer Instruktor, mit einer Ausbildung zum Autofahrlehrer im \n
      Jahr 2018 und einer zusätzlichen Ausbildung zum Lastwagen- \n
      und Busfahrlehrer im Jahr 2024.
  small_card_data: [bookshop:structure:AboutBannerCard]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  banner:
    options:
      preview:
        icon: 'image'
        text:
          - key: alt_text
          - 'Banner'
        subtext:
          - key: image_path
          - 'Update banner'
        image:
          - key: image_path
