# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Fahrschule Banner
  description: Fahrschule Banner
  icon: 'cottage'
  tags:
    - Image
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  h1: "Autofahren lernen leicht gemacht – Kategorie B"
  desc: "Lerne mit uns sicher Auto zu fahren! Unsere Fahrlektionen für die Kategorie B bereiten dich optimal auf die Theorie- und Praxisprüfung vor."

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  h1:
    options:
      preview:
        icon: 'text'
        text:
          - key: h1
          - 'Heading'
        subtext:
          - 'Update heading'
  desc:
    options:
      preview:
        icon: 'textarea'
        text:
          - key: desc
          - 'description'
        subtext:
          - 'Update description'
