# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Impressum Block
  description: Impressum Block
  icon: 'cottage'
  tags:
    - Image
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  header: Vertretungsberechtigte Person
  description: Geschäftsführer

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  header:
    type: text
    label: Header
    options:
      preview:
        icon: 'text'
        text:
          - key: header
        subtext:
          - 'Header Text'
  description:
    type: textarea
    label: Body 
    options:
      preview:
        icon: 'text'
        text:
          - key: description
        subtext:
          - 'description Text'
