# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Binding Contacts
  description: Binding Contacts
  icon: 'cottage'
  tags:
    - Image
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Jetzt unverbindlich \n kontaktieren
  description: >
    Gerne stelle ich mich bei dir persönlich vor. Zögere nicht mich anzurufen und mach dir selbst ein Bild von mir!
  socialLinks:
    - href: "https://facebook.com/"
      src: /facebook-brands-solid.svg
      alt: Facebook
      width: 30
      height: 30
    - href: "https://www.instagram.com/fahrschuleloyal"
      src: /square-instagram-brands-solid.svg
      alt: Instagram
      width: 34
      height: 34
    - href: "https://google.com"
      src: /google-brands-solid.svg
      alt: google
      width: 28
      height: 28
  button_text: Jetzt kontaktieren
  button_link: /kontakt

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  heading:
    options:
      preview:
        icon: 'text'
        text:
          - key: heading
          - 'heading Text'
        subtext:
          - 'Update heading text'
  button_text:
    options:
      preview:
        icon: 'text'
        text:
          - key: button_text
          - 'button_text'
        subtext:
          - 'Update text'
  button_link:
    options:
      preview:
        icon: 'text'
        text:
          - key: button_link
          - 'button_link'
        subtext:
          - 'Update text'
  description:
    options:
      preview:
        icon: 'text'
        text:
          - key: description
          - 'description Text'
        subtext:
          - 'Update description text'
  socialLinks:
    type: list
    label: socialLinks list
    item:
      type: group
      label: Social Link
      fields:
        href:
          type: text
          label: Name
          options:
            preview:
              icon: 'text'
              text:
                - key: href
              subtext:
                - 'name Text'
        src:
          options:
            preview:
              icon: 'image'
              text:
                - key: alt
                - 'Social Link Image'
              subtext:
                - key: src
                - 'Update Image'
              image:
                - key: src
        width:
          type: number
          label: Image width
          options:
            preview:
              text:
                - key: width
              subtext:
                - 'Member image width'
        height:
          type: number
          label: Image height
          options:
            preview:
              text:
                - key: height
              subtext:
                - 'Member image height'
        