# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Team
  description: About Team of This Site
  icon: 'cottage'
  tags:
    - Image
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  othercontainers: 
    - title: "Fahren ab 17 Jahren"
      paragraph:
        "Ab dem Alter von 17 Jahren kannst du einen Lernfahrausweis der Kategorie B beantragen und mit Fahrstunden beginnen. Für Personen unter 20 Jahren gilt jedoch eine Mindestlernzeit von 12 Monaten ab Erhalt des Lernfahrausweises."
    - title: "Automat oder Schaltung"
      paragraph:
        "Unabhängig davon, wie du dich entscheidest, bieten wir Fahrstunden für beide Varianten an. Doch welche ist die richtige Wahl für dich? <br /> <br /> Automatik : Einfacheres Lernen, möglicherweise weniger Fahrstunden und dadurch geringere Kosten. <br /> Geschaltet : Etwas anspruchsvolleres Lernen, aber die Fähigkeit, beide Varianten zu beherrschen."

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  othercontainers:
    type: list
    label: Other Containers
    item:
      type: group
      label: Containers
      fields:
        title:
          type: text
          label: Name
          options:
            preview:
              icon: 'text'
              text:
                - key: title
              subtext:
                - 'title Text'
        paragraph:
          type: textarea
          label: paragraph
          options:
            preview:
              icon: 'textarea'
              text:
                - key: paragraph
              subtext:
                - 'Member description'