# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Offer
  description: Offer of This Site
  icon: 'cottage'
  tags:
    - Text
    - Image

# Defines the structure of this component, as well as the default values
blueprint:
  offer_title: "Fahrschule Loyal in Schlieren \n für Auto, Bus, Lastwagen und Anhänger"
  offer_card: [bookshop:structure:OfferCard]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  offer_title:
    options:
      preview:
        text:
          - key: offer_title
          - Offer Title
        subtext:
          - 'Update Offer Title'